modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License, version 3"
[[mods]]
modId="incandescent_lib" #mandatory
version="1.0.0"
displayName="Incandescent Lib" #mandatory
credits="If only I could be so grossly incandescent" #optional
authors="nikgub_" #optional
description='''
A light-weight library providing API for entity animations, player animations and other little things
'''
logoFile="mod_logo_transparent.png"
[[dependencies.incandescent_lib]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.incandescent_lib]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
