/*
    Incandescent Lib, Minecraft Forge light-weight library
    Copyright (C) 2025, nikgub_

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package xyz.nikgub.incandescent.autogen_network;

import net.minecraftforge.network.NetworkDirection;
import xyz.nikgub.incandescent.autogen_network.core.IncandescentNetworkCore;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to automatically register a network packet
 * <p>
 * Classes marked with this annotation are not needed to be registered explicitly,
 * and their methods are automatically collected.
 * </p>
 * <p>
 * Decoder method must be a constructor that takes in {@link net.minecraft.network.FriendlyByteBuf}
 * </p>
 * <p>
 * If no decoder or encoder is present, they will be created from fields marked with
 * {@link Value}. However, if you intend on falling back on autogenerated decoder,
 * you must ensure that there is an available default constructor.
 * </p>
 *
 * @author Nikolay Gubankov (aka nikgub)
 * @see IncandescentNetworkCore
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface IncandescentPacket
{
    /**
     * Mod ID of the mod this packet is attached to
     *
     * @return Mod ID
     */
    String value ();

    NetworkDirection direction ();

    /**
     * Annotation to mark fields that contain data being sent
     * <p>
     * Fields marked with this annotation are used to automatically
     * build decoder and encoder, should there be none predefined
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    @interface Value
    {
        /**
         * Used to sort fields in a guaranteed way during encoder/decoder autogen,
         * since Java reflection does not guarantee that the order of the fields is preserved.
         *
         * @return {@code int} numeric ID of a field
         */
        int value () default Integer.MAX_VALUE;
    }

    /**
     * Annotation to mark packet's encoder method
     * <p>
     * Methods marked with this annotation are not used to process
     * encode data into packets to be sent
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    @interface Encoder
    {
    }

    /**
     * Annotation to mark packet's handler method
     * <p>
     * Methods marked with this annotation are not used to process
     * their packets once received by the other side
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    @interface Handler
    {
    }
}
